export const PROJECTS_DATA = [
  {
    id: "p1",
    title: "CyberRealm Arcade 3D",
    categoryKey: "games",
    categoryLabel: "VIDEOJUEGOS",
    icon: "🎮",
    desc: "Videojuego de acción 3D multijugador en tiempo real desarrollado con físicas avanzadas e integración multiplataforma.",
    tech: ["Unity 3D", "C#", "Multiplayer", "Steam API"],
    imageBg: "linear-gradient(135deg, #FF5500 0%, #FF8800 100%)",
  },
  {
    id: "p2",
    title: "Arvtech POS & Inventarios",
    categoryKey: "systems",
    categoryLabel: "SISTEMAS",
    icon: "⚙️",
    desc: "Sistema integral de punto de venta, inventarios en la nube y reportes financieros para negocios locales y cadenas.",
    tech: ["Next.js", "Node.js", "PostgreSQL", "Electron"],
    imageBg: "linear-gradient(135deg, #0284C7 0%, #38BDF8 100%)",
  },
  {
    id: "p3",
    title: "EcoConnect Mobile App",
    categoryKey: "mobile",
    categoryLabel: "MÓVIL",
    icon: "📱",
    desc: "Aplicación móvil para monitoreo inteligente de datos en tiempo real, alertas de rendimiento y analítica en vivo.",
    tech: ["React Native", "Firebase", "iOS", "Android"],
    imageBg: "linear-gradient(135deg, #059669 0%, #34D399 100%)",
  },
  {
    id: "p4",
    title: "Studio Web Platform",
    categoryKey: "web",
    categoryLabel: "WEB",
    icon: "💻",
    desc: "Portal web corporativo de alta velocidad con rendimiento optimizado, animación fluida y posicionamiento SEO avanzado.",
    tech: ["Next.js 16", "React 19", "SEO", "TailwindCSS"],
    imageBg: "linear-gradient(135deg, #7C3AED 0%, #A78BFA 100%)",
  },
  {
    id: "p5",
    title: "SmartCare Support Portal",
    categoryKey: "systems",
    categoryLabel: "SISTEMAS",
    icon: "🛠️",
    desc: "Plataforma de gestión de órdenes de soporte técnico, diagnósticos de equipos y cotizaciones automáticas para clientes.",
    tech: ["React", "Express", "REST API", "PDF Export"],
    imageBg: "linear-gradient(135deg, #EA580C 0%, #F97316 100%)",
  },
  {
    id: "p6",
    title: "Nexus Unity Tools",
    categoryKey: "games",
    categoryLabel: "VIDEOJUEGOS",
    icon: "🕹️",
    desc: "Colección de herramientas de automatización y scripts de optimización para motores de desarrollo de videojuegos.",
    tech: ["Unity Tools", "C# Editor", "Shader Graph"],
    imageBg: "linear-gradient(135deg, #DB2777 0%, #F472B6 100%)",
  },
];
